apiVersion: v1
kind: Pod
metadata:
  name: test-pod-app
  namespace: app
spec:
  containers:
  - name: test-container
    image: alpine
    command:
      - "/bin/sh"
      - "-c"
      - "apk add --no-cache curl && sleep 3600"  # Install curl and sleep
    stdin: true
    tty: true
