apiVersion: v1
kind: Pod
metadata: 
  name: authdb
  namespace: auth
  labels:
    app: authdatabase
spec:
  containers:
  - name: db
    image: postgres
    env:
    - name: POSTGRES_PASSWORD
      value: password
    - name: POSTGRES_USER
      value: user
    - name: POSTGRES_DB
      value: authDB
    - name: POSTGRES_HOST_AUTH_METHOD
      value: trust
    ports:
    - containerPort: 5432
  - name: pgadmin
    image: dpage/pgadmin4
    env:
    - name: PGADMIN_DEFAULT_USER
      value: my_pgadmin_user
    - name: PGADMIN_LISTEN_PORT
      value: "80"
    - name: PGADMIN_DEFAULT_SERVER
      value: localhost
    - name: PGADMIN_DEFAULT_SERVER_PORT
      value: "5432"
    - name: PGADMIN_DEFAULT_SERVER_DATABASE
      value: authDB
    - name: PGADMIN_DEFAULT_SERVER_USERNAME
      value: user
    - name: PGADMIN_DEFAULT_EMAIL
      value: v@email.com
    - name: PGADMIN_DEFAULT_PASSWORD
      value: password
    ports:
    - containerPort: 80